#!/bin/bash

# graphe : Tunnel IPv6

# créer les namespaces pour les hôtes
ip netns add h1
ip netns add h2
ip netns add r1
ip netns add r2

# créer le switch
ovs-vsctl add-br internet 
ovs-vsctl add-br s1 
ovs-vsctl add-br s2

# créer les liens
ip link add h1-eth0 type veth peer name s1-h1
ip link add h2-eth0 type veth peer name s2-h2

ip link add r1-eth0 type veth peer name s1-r1
ip link add r1-eth1 type veth peer name internet-r1

ip link add r2-eth0 type veth peer name s2-r2
ip link add r2-eth1 type veth peer name internet-r2

# accrocher les liens aux namespaces
ip link set h1-eth0 netns h1
ip link set h2-eth0 netns h2
ip link set r1-eth0 netns r1
ip link set r1-eth1 netns r1
ip link set r2-eth0 netns r2
ip link set r2-eth1 netns r2

# connecter les liens au switch
ovs-vsctl add-port s1 s1-h1 
ovs-vsctl add-port s1 s1-r1
ovs-vsctl add-port s2 s2-h2 
ovs-vsctl add-port s2 s2-r2

ovs-vsctl add-port internet internet-r1
ovs-vsctl add-port internet internet-r2

# activer les interfaces du namespace root
ip link set dev s1-h1 up
ip link set dev s2-h2 up
ip link set dev s1-r1 up
ip link set dev s2-r2 up
ip link set dev internet-r1 up
ip link set dev internet-r2 up

# activer les interfaces des namespaces h1 et h2 
ip netns exec h1 ip link set dev h1-eth0 up
ip netns exec h2 ip link set dev h2-eth0 up
ip netns exec h1 ip link set dev lo up
ip netns exec h2 ip link set dev lo up

# activer les interfaces des namespaces r1 et r2 
ip netns exec r1 ip link set dev r1-eth0 up
ip netns exec r1 ip link set dev r1-eth1 up
ip netns exec r2 ip link set dev r2-eth0 up
ip netns exec r2 ip link set dev r2-eth1 up
ip netns exec r1 ip link set dev lo up
ip netns exec r2 ip link set dev lo up

# configurer les réseaux sur s1, s2 et internet
ip netns exec h1 ip a add dev h1-eth0 172.16.32.1/24
ip netns exec r1 ip a add dev r1-eth0 172.16.32.254/24

ip netns exec h2 ip a add dev h2-eth0 192.168.87.1/24
ip netns exec r2 ip a add dev r2-eth0 192.168.87.254/24

ip netns exec r1 ip a add dev r1-eth1 10.10.0.1/24
ip netns exec r2 ip a add dev r2-eth1 10.10.0.2/24

# configurer les routes sur r1 et r2 
ip netns exec r1 ip r add 192.168.87.0/24 via 10.10.0.2
ip netns exec r2 ip r add 172.16.32.0/24 via 10.10.0.1

# configurer la route par défaut sur h1 et h2
ip netns exec h1 ip r add default via 172.16.32.254
ip netns exec h2 ip r add default via 192.168.87.254

# activer le routage sur r1 et r2
ip netns exec r1 sudo sysctl net.ipv4.conf.all.forwarding=1
ip netns exec r2 sudo sysctl net.ipv4.conf.all.forwarding=1

